{
  "timezone": "America/New_York",
  "slippage_points": 0.0,
  "session_start": "08:00",
  "session_end": "12:00",
  "resample_minutes": 3,
  "max_daily_loss": 200.0,
  "max_trades_per_day": 6,
  "max_trades_per_hour": 3,
  "min_trades_for_stats_warning": 100,
  "meta_file_support_enabled": false,
  "require_contract": true,
  "outdir": "./outputs",
  "strict_validation": false,
  "contracts": {
    "MES": {
      "label": "Micro E-mini S&P 500",
      "dollars_per_point": 5.0,
      "tick_size": 0.25,
      "commission_roundtrip": 1.74,
      "position_contracts": 1,
      "notes": "Micro e-mini S&P"
    },
    "MNQ": {
      "label": "Micro E-mini Nasdaq-100",
      "dollars_per_point": 2.0,
      "tick_size": 0.25,
      "commission_roundtrip": 1.74,
      "position_contracts": 3,
      "notes": "Micro e-mini NASDAQ"
    },
    "ES": {
      "label": "E-mini S&P 500",
      "dollars_per_point": 50.0,
      "tick_size": 0.25,
      "commission_roundtrip": 1.74,
      "position_contracts": 1,
      "notes": "E-mini S&P"
    }
  },
  "orb": {
    "open_range_minutes": 20,
    "require_close_outside_orb": true,
    "breakout_buffer_points": 0.5,
    "require_volume_confirmation": true,
    "volume_lookback": 10,
    "volume_multiplier": 1.5,
    "take_profit_r": [
      1.4,
      2.4
    ],
    "stop_policy": "atr",
    "atr_multiplier_stop": 1.0,
    "stop_fixed_points": 3.0,
    "round_stops_to_tick": true
  },
  "pullback": {
    "ema_fast": 13,
    "ema_slow": 30,
    "pullback_bars": 3,
    "atr_period": 21,
    "atr_multiplier_stop": 2.2,
    "target_r": 3.5,
    "stop_fixed_points": 7.0,
    "require_bias_by_ema": true,
    "round_stops_to_tick": true,
    "tick_size": 0.25,
    "session_start": "08:00",
    "session_end": "12:00"
  },
  "vwap": {
    "vwap_extension": 6.0,
    "extension_periods": 3,
    "volume_threshold": 0.4,
    "volume_lookback": 20,
    "swing_lookback": 4,
    "stop_buffer": 0.5,
    "target_r": 1.5,
    "stop_r": 0.75,
    "session_start": "08:00",
    "session_end": "12:00",
    "require_trend_alignment": true
  },
  "scalping": {
    "fast_ema": 8,
    "medium_ema": 25,
    "slow_ema": 50,
    "rsi_period": 14,
    "rsi_overbought": 75,
    "rsi_oversold": 25,
    "rsi_midline": 50,
    "macd_fast": 12,
    "macd_slow": 26,
    "macd_signal": 9,
    "threshold_points": 2.0,
    "target_r": 2.0,
    "stop_r": 0.75,
    "take_profit_ticks": 10,
    "stop_loss_ticks": 8,
    "tick_size": 0.25,
    "session_start": "10:00",
    "session_end": "12:00"
  },
  "trade_management": {
    "time_stop_minutes": 10,
    "reentry_cooldown_same_side_minutes": 15,
    "force_exit_on_daily_loss": true,
    "daily_loss_threshold": 200.0,
    "max_trades_day": 6,
    "max_trades_hour": 3
  },
  "logging": {
    "tag_trades": true,
    "tags": [
      "orb",
      "vwapsync",
      "vol_confirm",
      "time_stop"
    ]
  }
}