# config.yaml - production-ready v1 defaults
timezone: "America/New_York"
# commission_roundtrip: 1.74  # Moved to contract-specific settings
slippage_points: 0.0
session_start: "08:00"
session_end: "12:00"
resample_minutes: 15
max_daily_loss: 200.0
max_trades_per_day: 6
min_trades_for_stats_warning: 100
meta_file_support_enabled: false
require_contract: true
outdir: "./outputs"
strict_validation: false    # set true to enable strict price-scale checks

contracts:
  MES:
    label: "Micro E-mini S&P 500"
    dollars_per_point: 5.0
    tick_size: 0.25
    commission_roundtrip: 1.74
    position_contracts: 10
    notes: "Micro e-mini S&P"
  MNQ:
    label: "Micro E-mini Nasdaq-100"
    dollars_per_point: 2.0
    tick_size: 0.25
    commission_roundtrip: 1.74
    position_contracts: 3
    notes: "Micro e-mini NASDAQ"
  ES:
    label: "E-mini S&P 500"
    dollars_per_point: 50.0
    tick_size: 0.25
    commission_roundtrip: 1.74
    position_contracts: 1
    notes: "E-mini S&P"

orb:
  open_range_minutes: 30       # Longer from 15 - more significant ranges
  require_volume_confirmation: true  # Keep enabled
  volume_lookback: 10           # Longer from 5 - more reliable volume filter
  take_profit_r: [2.2, 3.2]    # Higher from [1.0, 2.0] - better risk/reward
  stop_policy: "atr"            # Change from "structure" - more dynamic
  atr_multiplier_stop: 1.2    # Wider from 1.0 - reduce stop-outs
  stop_fixed_points: 6.0        # Wider from 4.0 - fallback for noise
  round_stops_to_tick: true     # Keep  

pullback:
  ema_fast: 13
  ema_slow: 30
  pullback_bars: 3
  atr_period: 21
  atr_multiplier_stop: 2.2
  target_r: 3.5
  stop_fixed_points: 7.0
  require_bias_by_ema: true
  round_stops_to_tick: true
  tick_size: 0.25
  session_start: "08:00"
  session_end: "12:00"

vwap:
  # VWAP Fade Strategy parameters
  vwap_extension: 6.0           # Points from VWAP to consider extended
  extension_periods: 3          # How many periods price should be extended
  volume_threshold: 0.4         # Ratio to average volume to consider low volume
  volume_lookback: 20           # Periods to calculate average volume
  swing_lookback: 4             # Periods to identify recent swing
  stop_buffer: 0.5              # Additional buffer beyond swing for stop
  target_r: 1.5                 # Target risk/reward ratio
  stop_r: 0.75                  # Stop loss as R multiple
  session_start: "08:00"        # Session start time
  session_end: "12:00"          # Session end time

scalping:
  # MES Scalping Strategy parameters
  # EMA parameters
  fast_ema: 8                   # Fast EMA period
  medium_ema: 25                # Medium EMA period
  slow_ema: 50                  # Slow EMA period
  
  # RSI parameters
  rsi_period: 14                # RSI calculation period
  rsi_overbought: 75            # RSI overbought threshold
  rsi_oversold: 25              # RSI oversold threshold
  rsi_midline: 50               # RSI midline for trend confirmation
  
  # MACD parameters
  macd_fast: 12                 # MACD fast period
  macd_slow: 26                 # MACD slow period
  macd_signal: 9                # MACD signal line period
  
  # Trade management
  threshold_points: 2.0         # Points for signal confirmation
  target_r: 2.0                 # Target risk/reward ratio
  stop_r: 0.75                  # Stop loss as R multiple
  take_profit_ticks: 10         # Take profit in ticks
  stop_loss_ticks: 8            # Stop loss in ticks
  
  # Contract specifications
  tick_size: 0.25               # MES tick size in points
  
  # Session filter
  session_start: "10:00"        # Session start time
  session_end: "12:00"          # Session end time

ema8_21:
  # Ultra-Selective 8/21 EMA Strategy for MES Futures
  # Based on 30-minute charts for day trading
  
  # Trading session (excludes first 15 minutes)
  session_start: "09:45"        # Start after market open
  session_end: "14:30"          # End before market close
  timezone: "America/New_York"
  
  # EMA indicators
  fast_ema_period: 8            # Fast EMA period
  slow_ema_period: 21           # Slow EMA period
  
  # RSI settings
  rsi_period: 14                # RSI calculation period
  rsi_overbought: 60            # RSI overbought threshold
  rsi_oversold: 40              # RSI oversold threshold
  
  # Trend strength filter
  # trend_strength_threshold: 0.8 # Minimum trend strength percentage
  trend_strength_threshold: 0.001 # Minimum trend strength percentage
  
  # Exit rules - take profit levels as percentages  
  take_profit_levels: [6.0, 10.0] # Two take profit levels (% of initial risk)
  take_profit_sizes: [70, 30]     # Position sizes for each level (%)
  stop_loss_percentage: 2.5       # Stop loss as percentage of entry price
  
  # Trailing stop
  trailing_stop_percentage: 1.8   # Trailing stop percentage
  trailing_activation_rr: 1.0     # Risk/reward ratio to activate trailing
  
  # Risk management
  account_size: 25000             # Account size for position sizing
  risk_per_trade_percentage: 1.0  # Risk per trade as % of account
  max_daily_loss_percentage: 5.0  # Maximum daily loss percentage
  max_open_positions: 2           # Maximum concurrent positions
  
  # Position sizing
  default_position_size: 10       # Default contract size
  max_position_size: 20          # Maximum contracts per trade
  
  # Execution
  commission_per_contract: 2.0    # Commission per contract
  point_value: 5.0               # Point value for MES
  slippage_points: 1.0           # Slippage in points