timezone: America/New_York
commission_roundtrip: 1.74
slippage_points: 0.0
session_start: 08:00
session_end: '12:00'
resample_minutes: 15
max_daily_loss: 200.0
max_trades_per_day: 6
meta_file_support_enabled: false
contracts:
  MES: &id001
    label: Micro E-mini S&P 500
    dollars_per_point: 5.0
    tick_size: 0.25
    commission_roundtrip: 1.74
    position_contracts: 2
    notes: Micro e-mini S&P
  MNQ:
    label: Micro E-mini Nasdaq-100
    dollars_per_point: 2.0
    tick_size: 0.25
    commission_roundtrip: 1.74
    position_contracts: 3
    notes: Micro e-mini NASDAQ
  ES:
    label: E-mini S&P 500
    dollars_per_point: 50.0
    tick_size: 0.25
    commission_roundtrip: 1.74
    position_contracts: 1
    notes: E-mini S&P
min_trades_for_stats_warning: 100
require_contract: true
outdir: ./test_outputs
strict_validation: false
orb:
  open_range_minutes: 30
  require_volume_confirmation: true
  volume_lookback: 10
  take_profit_r:
  - 2.2
  - 3.2
  stop_policy: atr
  atr_multiplier_stop: 1.2
  stop_fixed_points: 6.0
  round_stops_to_tick: true
pullback:
  ema_fast: 13
  ema_slow: 30
  pullback_bars: 3
  atr_period: 21
  atr_multiplier_stop: 2.2
  target_r: 3.5
  stop_fixed_points: 7.0
  require_bias_by_ema: true
  round_stops_to_tick: true
  tick_size: 0.25
  session_start: 08:00
  session_end: '12:00'
  use_atr_stops: false
  use_fixed_stops: false
  use_sr_stops: true
  sr_lookback_bars: 20
  sr_min_touches: 2
  sr_buffer_points: 0.5
  round_number_intervals:
  - 25
  - 50
  - 100
  stop_selection: tightest
vwap:
  threshold_points: 2.0
  vwap_extension: 6.0
  extension_periods: 3
  volume_threshold: 0.4
  volume_lookback: 20
  swing_lookback: 4
  stop_buffer: 0.5
  target_r: 1.5
  stop_r: 0.75
  session_start: 08:00
  session_end: '12:00'
scalping:
  fast_ema: 8
  medium_ema: 25
  slow_ema: 50
  rsi_period: 14
  rsi_overbought: 75
  rsi_oversold: 25
  rsi_midline: 50
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  threshold_points: 2.0
  target_r: 2.0
  stop_r: 0.75
  take_profit_ticks: 10
  stop_loss_ticks: 8
  tick_size: 0.25
  session_start: '10:00'
  session_end: '12:00'
ema8_21:
  session_start: 09:45
  session_end: '14:30'
  timezone: America/New_York
  fast_ema_period: 8
  slow_ema_period: 21
  rsi_period: 14
  rsi_overbought: 70
  rsi_oversold: 30
  trend_strength_threshold: 0.02
  take_profit_levels:
  - 4.0
  - 8.0
  take_profit_sizes:
  - 50
  - 50
  stop_loss_percentage: 0.25
  trailing_stop_percentage: 1.8
  trailing_activation_rr: 1.0
  account_size: 2000
  risk_per_trade_percentage: 2.0
  max_daily_loss_percentage: 6.0
  max_open_positions: 1
  default_position_size: 2
  max_position_size: 3
  commission_per_contract: 1.74
  point_value: 5.0
  slippage_points: 1.0
resolved_contract: MES
contract_meta: *id001
